### ISSUE TITLE
isnt working

### ISSUE THREAD

**Issue by Zathuraboy** [Ad5001/pmt.mcpe.fun#2]
Hey there brotha, Your "pmt.mcpe.fun" is not Working it Just Says "page generated in 0.228432847" and dosent generate any file, yes the files are correct im sure.

**Comment by XFizzer** [comment]
It's your plugin not the website, works perfectly for me

**Comment by Ad5001** [comment]
I had to make an update on my VPS. Services are back ;)

**Comment by Zathuraboy** [comment]
Oh thanks
